### ISSUE TITLE
Getting connection refused error 

### ISSUE THREAD

**Issue by ali-shabani** [aleskxyz/reality-ezpz#23]
سلام. من هسته ی sing-box رو روی سرورم فعال کردم ولی هر چند ساعت یه بار (فکر میکنم دیگه ۲ ساعت یه بار)  توی لاگش من این ارور رو میبینم:
container: gzxhwq/sing-box
```
inbound/vless[1]: process connection from xxx.xxx.xxx.xxx:49170: dial tcp 10.255.255.10:1080: connect: connection refused

```
که اون `xxx` ها آیپی سیستم خودمه (نه سرور) البته توی هر خطر اررور بعضا پورتش تفاوت میکنه (من فقطم با سیستم خودم به سرور وصل میشم و به خاطر همین آیپی همیشه یکیه)
تنها راه حل هم اینه که برم دستی اسکریپت رو restart کنم. من لاگ بیشتری به جز این خط اررور که تکرار میشه توی سرور نمیبینم که بخوام اطلاعات بیشتری بدم. ممنون میشم کمک کنی مشکل رو حل کنیم.

**Comment by ali-shabani** [comment]
البته بیشتر که چک کردم اینم اضافه شده:
```
inbound/vless[1]: process connection from xxx.xxx.xxx.xxx:59726: flow mismatch: expected xtls-rprx-vision, but got none

```

**Comment by aleskxyz** [comment]
سلام
من داکر ایمیج وارپ رو به اخرین نسخه کلاینت لینوکس اپدیت کردم، چک کنید ببینید حل شده یا نه.

**Comment by ali-shabani** [comment]
من یه سوالی که داشتم اینه که چرا توی این قسمت
```yaml
warp:
    image: ${image[warp]}
    expose:
    - 1080
    restart: always
    environment:
      FAMILIES_MODE: $([[ ${config[safenet]} == ON ]] && echo 'full' || echo 'off')
      WARP_LICENSE: ${config[warp_license]}
    volumes:
    - ./warp:/var/lib/cloudflare-warp
    networks:
      reality:
        ipv4_address: 10.255.255.10"
```

اومدید یه نتورک تعریف کردید با آیپی. چرا از bridge استفاده نکردید. و توی تنظیمات outbound فقط اسم همین کانتینر که warp میشه رو بهش پاس ندادید به جای آیپی. و اینکه به خاطر داخلی بودن نتورک اصلا نیازی به expose کردن پورت ۱۰۸۰ به بیرون هم نیستید. (البته من نمیدونم که چرا این کارو کردید صرفا دلیلشو میپرسم)
چون توی داکر شما هر پورتی رو که expose میکنید از بیرون بهش دسترسی دارن و من همین مشکل رو روی سرور خودم با redis داشتم که اگه پورت expose باشه قشنگ به چند ساعت نرسیده همش redis من readonly میشد و مثله اینکه اتک میزدن بهش. که بعدا با ufw و اسکریپتی که برای حل مشکل بین داکر و ufw داره وقتی پورت رو بستم دیگه مشکلی نبود.
